[compiler.solc]
include_paths = ["node_modules", "lib"]
exclude_paths = ["node_modules", "lib", "tests"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/",
]
via_IR = true
